apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-code-education
  labels:
    app: nginx-code-education

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-code-education
  
  template:
    metadata:
      labels:
        app: nginx-code-education
    spec:
      containers:
      - name: nginx-code-education
        image: rodrigotc94/nginx:desafiok8s
        ports:
        - containerPort: 80
      
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf
          readOnly: true

      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf-code
          items:
            - key: nginx.conf
              path: nginx.conf
